version: '3.7'
services:
  loans-discovery-server:
     build: .
     hostname: eureka-server
     container_name: eureka-server
     ports:
       - '9713:9713'
     volumes:
      - ./discoveryLogs:/app/logs
     restart: always
     deploy:
       resources:
         limits:
           memory: 256m
     networks:
       - esb-docker-network

networks:
  esb-docker-network:
    external: true

